# None

In [1]:
None

In [2]:
print(None)

None


In [3]:
type(None)

NoneType

In [4]:
__builtins__

<module 'builtins' (built-in)>

In [5]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [6]:
getattr(__builtins__, "None")

In [7]:
# Singleton
another_none = type(None)()

In [8]:
another_none is None

True

In [9]:
another_none == None

True

In [10]:
id(None)

9447968

In [11]:
id(another_none)

9447968

In [12]:
class AnotherNone(type(None)):
    pass

TypeError: type 'NoneType' is not an acceptable base type

# NotImplemented

In [13]:
class SmallFloat:
    def __init__(self, value):
        self.value = value
    
    def __lt__(self, other):
        if isinstance(other, (SmallFloat, SmallInt)):
            print("Call SmallFloat.__lt__...")
            return self.value < other.value
        return NotImplemented
    
    def __gt__(self, other):
        print("Not implement SmallFloat.__gt__")
        return NotImplemented

In [14]:
f1 = SmallFloat(10.0)
f2 = SmallFloat(20.0)
f1 > f2

Not implement SmallFloat.__gt__


NameError: name 'SmallInt' is not defined

In [15]:
class SmallFloat:
    def __init__(self, value):
        self.value = value
    
    def __lt__(self, other):
        if isinstance(other, (SmallFloat, SmallInt)):
            print("Call SmallFloat.__lt__...")
            return self.value < other.value
        return NotImplemented
    
    def __gt__(self, other):
        print("Not implement SmallFloat.__gt__")
        raise NotImplementedError

In [16]:
f1 = SmallFloat(10.0)
f2 = SmallFloat(20.0)
f1 > f2

Not implement SmallFloat.__gt__


NotImplementedError: 

In [17]:
bool(NotImplemented)

True

# Ellipsis

In [18]:
Ellipsis

Ellipsis

In [19]:
type(Ellipsis)

ellipsis

In [20]:
...

Ellipsis

In [21]:
import numpy as np

In [22]:
x = np.arange(16).reshape(2, 2, 4)

In [23]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [24]:
x[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [25]:
x[1,...]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
x[...,1]

array([[ 1,  5],
       [ 9, 13]])

In [27]:
x[1, ..., 1]

array([ 9, 13])

In [28]:
x[..., 1, 1]

array([ 5, 13])