# None

In [12]:
None

In [13]:
print(None)

None


In [14]:
type(None)

NoneType

In [15]:
__builtins__

<module 'builtins' (built-in)>

In [16]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [17]:
getattr(__builtins__, "None")

In [18]:
# Singleton
another_none = type(None)()

In [19]:
another_none is None

True

In [20]:
another_none == None

True

In [21]:
id(None)

9447968

In [22]:
id(another_none)

9447968

In [23]:
class AnotherNone(type(None)):
    pass

TypeError: type 'NoneType' is not an acceptable base type

# NotImplemented

In [24]:
class SmallFloat:
    def __init__(self, value):
        self.value = value
    
    def __lt__(self, other):
        if isinstance(other, (SmallFloat, SmallInt)):
            print("Call SmallFloat.__lt__...")
            return self.value < other.value
        return NotImplemented
    
    def __gt__(self, other):
        print("Not implement SmallFloat.__gt__")
        return NotImplemented

In [25]:
f1 = SmallFloat(10.0)
f2 = SmallFloat(20.0)
f1 > f2

Not implement SmallFloat.__gt__


NameError: name 'SmallInt' is not defined

In [26]:
class SmallFloat:
    def __init__(self, value):
        self.value = value
    
    def __lt__(self, other):
        if isinstance(other, (SmallFloat, SmallInt)):
            print("Call SmallFloat.__lt__...")
            return self.value < other.value
        return NotImplemented
    
    def __gt__(self, other):
        print("Not implement SmallFloat.__gt__")
        raise NotImplementedError

In [27]:
f1 = SmallFloat(10.0)
f2 = SmallFloat(20.0)
f1 > f2

Not implement SmallFloat.__gt__


NotImplementedError: 

In [28]:
bool(NotImplemented)

True

# Ellipsis

In [29]:
Ellipsis

Ellipsis

In [30]:
type(Ellipsis)

ellipsis

In [31]:
...

Ellipsis

In [32]:
import numpy as np

In [33]:
x = np.arange(16).reshape(2, 2, 4)

In [34]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [35]:
x[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
x[1,...]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
x[...,1]

array([[ 1,  5],
       [ 9, 13]])

In [38]:
x[1, ..., 1]

array([ 9, 13])

In [39]:
x[..., 1, 1]

array([ 5, 13])

# Callables

## User-defined function

In [40]:
def run(a: int, b: float, c: float = 1.0) -> float:
    """Process numbers"""
    return a + b + c

In [41]:
run.__doc__

'Process numbers'

In [42]:
run.__name__

'run'

In [43]:
run.__qualname__

'run'

In [44]:
run.__module__

'__main__'

In [45]:
run.__defaults__

(1.0,)

In [46]:
run.__code__

<code object run at 0x7f816d466190, file "<ipython-input-40-8fe405244565>", line 1>

In [47]:
run.__globals__

]),
  36: array([[ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
  37: array([[ 1,  5],
         [ 9, 13]]),
  38: array([ 9, 13]),
  39: array([ 5, 13]),
  41: 'Process numbers',
  42: 'run',
  43: 'run',
  44: '__main__',
  45: (1.0,),
  46: <code object run at 0x7f816d466190, file "<ipython-input-40-8fe405244565>", line 1>},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f816824d8b0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x7f816827c1f0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x7f816827c1f0>,
 '_': <code object run at 0x7f816d466190, file "<ipython-input-40-8fe405244565>", line 1>,
 '__': (1.0,),
 '___': '__main__',
 '_rwho_ls': ['os', 'sio', 'sys'],
 'os': <module 'os' from '/usr/lib/python3.8/os.py'>,
 'sys': <module 'sys' (built-in)>,
 '_i': 'run.__code__',
 '_ii': 'run.__defaults__',
 '_iii': 'run.__module__',
 '_i1': 'import scipy.io as sio',
 'sio': <module 'scipy.io' from '/home/jian

In [48]:
run.__dict__

{}

In [49]:
run.__closure__

In [50]:
run.__annotations__

{'a': int, 'b': float, 'c': float, 'return': float}

In [51]:
run.__kwdefaults__

## Instance method

In [52]:
class User:
    """Customized user class"""

    def __init__(self, name: str, password: str, active: bool=True):
        """Initialize user class"""
        self.name = name
        self.password = password
    
    def __repr__(self):
        """User string representation"""
        return f"<User: {self.name}>"

    def change_password(self, new_password):
        """User changes password"""
        self.password = new_password

In [53]:
user = User(name="tester", password="123456")

In [54]:
user.change_password.__doc__

'User changes password'

In [55]:
user.change_password.__self__

<User: tester>

In [56]:
user.change_password.__func__

<function __main__.User.change_password(self, new_password)>

In [57]:
user.change_password.__func__.__name__

'change_password'

In [58]:
user.change_password.__func__.__module__

'__main__'

## Generattor functions

In [80]:
def generate_numbers(n):
    i = 0
    while i < n:
        yield i
        i += 1

In [81]:
numbers = generate_numbers(5)

In [82]:
numbers

<generator object generate_numbers at 0x7f813352eb30>

In [83]:
next(numbers)

0

In [84]:
numbers.__next__()

1

In [85]:
for i in numbers:
    print(i)

2
3
4


In [86]:
next(numbers)

StopIteration: 

## Coroutine functions

In [ ]:
import asyncio

async def say():
    print("Hello")


# Modules

In [59]:
import scipy.io as sio

In [60]:
sio.__name__

'scipy.io'

In [61]:
sio.__loader__

In [62]:
sio.__spec__

ModuleSpec(name='scipy.io', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8168205cd0>, origin='/home/jianli/.virtualenvs/dev/lib/python3.8/site-packages/scipy/io/__init__.py', submodule_search_locations=['/home/jianli/.virtualenvs/dev/lib/python3.8/site-packages/scipy/io'])

In [63]:
sio.__path__

['/home/jianli/.virtualenvs/dev/lib/python3.8/site-packages/scipy/io']

In [64]:
sio.__file__

'/home/jianli/.virtualenvs/dev/lib/python3.8/site-packages/scipy/io/__init__.py'

In [65]:
sio.__cached__

'/home/jianli/.virtualenvs/dev/lib/python3.8/site-packages/scipy/io/__pycache__/__init__.cpython-38.pyc'

In [66]:
sio.__dict__

{'__name__': 'scipy.io',
 '__doc__': "\n==================================\nInput and output (:mod:`scipy.io`)\n==================================\n\n.. currentmodule:: scipy.io\n\nSciPy has many modules, classes, and functions available to read data\nfrom and write data to a variety of file formats.\n\n.. seealso:: `NumPy IO routines <https://www.numpy.org/devdocs/reference/routines.io.html>`__\n\nMATLAB® files\n=============\n\n.. autosummary::\n   :toctree: generated/\n\n   loadmat - Read a MATLAB style mat file (version 4 through 7.1)\n   savemat - Write a MATLAB style mat file (version 4 through 7.1)\n   whosmat - List contents of a MATLAB style mat file (version 4 through 7.1)\n\nIDL® files\n==========\n\n.. autosummary::\n   :toctree: generated/\n\n   readsav - Read an IDL 'save' file\n\nMatrix Market files\n===================\n\n.. autosummary::\n   :toctree: generated/\n\n   mminfo - Query matrix info from Matrix Market formatted file\n   mmread - Read matrix from Matrix Mark